force_cast: warning
type_name:
  allowed_symbols:
    - _
identifier_name:
  min_length:
    warning: 3
line_length:
    warning: 200
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
